title: cellworld
description: A experimental platform for controllable, repeatable animal-robot interactions, within a space that can be varied from fully observable open arenas to partially observable cluttered arenas, or configured into conventional assays.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
